# Kubernetes Secrets Configuration
# Native Kubernetes secret management with best practices

---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: myapp-prod
type: Opaque
stringData:
  # In production, use external secret operators like:
  # - External Secrets Operator
  # - Sealed Secrets
  # - Vault Secrets Operator
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  connection-string: postgresql://${DB_USERNAME}:${DB_PASSWORD}@prod-db:5432/myapp

---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: myapp-prod
type: Opaque
stringData:
  payment-gateway: ${PAYMENT_API_KEY}
  analytics: ${ANALYTICS_API_KEY}
  email-service: ${EMAIL_API_KEY}

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate
  namespace: myapp-prod
type: kubernetes.io/tls
data:
  # Base64 encoded certificate and key
  tls.crt: LS0tLS1CRUdJTi...
  tls.key: LS0tLS1CRUdJTi...

---
# Deployment using secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myapp:latest
          env:
            # Environment variables from secrets
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: payment-gateway

          # Mount secrets as files
          volumeMounts:
            - name: db-connection
              mountPath: /etc/secrets/database
              readOnly: true
            - name: tls-certs
              mountPath: /etc/ssl/certs
              readOnly: true

      volumes:
        - name: db-connection
          secret:
            secretName: database-credentials
            items:
              - key: connection-string
                path: connection.txt
        - name: tls-certs
          secret:
            secretName: tls-certificate

---
# External Secrets Operator Example
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials-external
  namespace: myapp-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore

  target:
    name: database-credentials
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: myapp/database
        property: username

    - secretKey: password
      remoteRef:
        key: myapp/database
        property: password

---
# Sealed Secret Example (encrypted)
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-credentials-sealed
  namespace: myapp-prod
spec:
  encryptedData:
    username: AgCZ8rq7M3F...
    password: AgBkK2vM9XL...
  template:
    metadata:
      name: database-credentials
      namespace: myapp-prod
